<a href="https://colab.research.google.com/github/tuxlimr/Celery_Preprocessing/blob/master/52WeekHIgh_Low_and_Other_Breakout.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install yfinance --quiet

In [7]:
import yfinance as yf
import pandas as pd

def is_near_52_week_high_low(ticker_symbol, tolerance=0.05):
    stock = yf.Ticker(ticker_symbol)
    data = stock.history(period="1y")

    high_52_week = data['Close'].max()
    low_52_week = data['Close'].min()
    last_close = data['Close'].iloc[-1]

    near_high = last_close >= (1 - tolerance) * high_52_week
    near_low = last_close <= (1 + tolerance) * low_52_week

    return near_high, near_low, high_52_week, low_52_week, last_close

def check_stocks(stocks, tolerance=0.05):
    data_list = []

    for stock_symbol in stocks:
        near_high, near_low, high_52_week, low_52_week, last_close = is_near_52_week_high_low(stock_symbol, tolerance)

        data_list.append({
            'Stock': stock_symbol,
            'Last Close': last_close,
            '52-Week High': high_52_week,
            '52-Week Low': low_52_week,
            'Is near 52-week high': near_high,
            'Is near 52-week low': near_low
        })

    # Create a DataFrame
    df = pd.DataFrame(data_list)

    return df

if __name__ == "__main__":
    # List of stock ticker symbols


    NiftyIT = ['INFY.NS', 'TCS.NS']
    NiftyMetal = ['HINDALCO.NS','TATASTEEL.NS','JINDALSTEL.NS', 'VEDL.NS','ICICIBANK.NS']
    NiftyTelecom = ['BHARTIARTL.NS','TATACOMM.NS','IDEA.NS']
    NityBank = ['HDFCBANK.NS','PNB.NS','SBIN.NS', 'ICICIBANK.NS','AXISBANK.NS','CANBK.NS','BANKBARODA.NS','INDUSINDBK.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'J&KBANK.NS', 'IDBI.NS']
    NIftyFMCG = ['BAJAJCON.NS','ITC.NS', 'HINDUNILVR.NS', 'DABUR.NS','COLPAL.NS']

    ticker = NiftyIT + NiftyMetal + NiftyTelecom + NityBank + NIftyFMCG


    # Tolerance of 5% (adjust as needed)
    tolerance = 0.05

    # Get DataFrame
    df = check_stocks(ticker, tolerance)

    # Print DataFrame
df

,Stock,Last Close,52-Week High,52-Week Low,Is near 52-week high,Is near 52-week low
0,INFY.NS,1478.699951,1613.416748,1191.149658,False,False
1,TCS.NS,3621.399902,3621.399902,2966.460205,True,False
2,HINDALCO.NS,472.600006,499.687286,382.452759,False,False
3,TATASTEEL.NS,125.900002,131.949997,96.403557,True,False
4,JINDALSTEL.NS,683.450012,713.549988,427.221558,True,False
5,VEDL.NS,222.699997,285.600006,208.350006,False,False
6,ICICIBANK.NS,945.200012,992.450012,803.882202,True,False
7,BHARTIARTL.NS,926.049988,936.150024,736.715881,True,False
8,TATACOMM.NS,1837.800049,1932.750000,1148.043335,True,False
9,IDEA.NS,10.950000,12.100000,5.800000,False,False
10,HDFCBANK.NS,1534.050049,1728.199951,1377.799561,False,False
11,PNB.NS,76.750000,83.199997,35.245003,False,False
12,SBIN.NS,594.250000,620.200012,495.716980,True,False
13,ICICIBANK.NS,945.200012,992.450012,803.882202,True,False
14,AXISBANK.NS,1000.950012,1041.050049,753.549683,True,False
15,CANBK.NS,375.299988,384.450012,214.213501,True,False
16,BANKBARODA.NS,215.300003,217.850006,125.867088,True,False
17,INDUSINDBK.NS,1434.800049,1458.250000,991.423584,True,False
18,RBLBANK.NS,247.500000,255.600006,119.277588,True,False
19,MAHABANK.NS,48.549999,49.500000,15.696742,True,False
20,J&KBANK.NS,114.000000,114.000000,27.784285,True,False
21,IDBI.NS,69.750000,72.550003,41.619194,True,False
22,BAJAJCON.NS,231.649994,258.049988,143.949997,False,False
23,ITC.NS,442.149994,492.149994,319.266846,False,False
24,HINDUNILVR.NS,2499.399902,2757.100098,2386.607910,False,True
25,DABUR.NS,547.150024,601.579163,502.643066,False,False
26,COLPAL.NS,1992.550049,2067.899902,1424.127441,True,False

### Breakout

In [10]:
import yfinance as yf
import pandas as pd

def check_breakout(ticker_symbol):
    stock = yf.Ticker(ticker_symbol)
    data = stock.history(period="4d")  # Get 2 days of data including today

    # Extract previous day's and today's closing prices
    prev_close = data['Close'].iloc[0]  # Previous day's closing price
    today_close = data['Close'].iloc[1]  # Today's closing price

    # Check if there's a breakout
    is_breakout = today_close > prev_close

    return {
        'Stock': ticker_symbol,
        'Previous Day\'s Close': prev_close,
        'Today\'s Close': today_close,
        'Breakout Detected': is_breakout
    }

if __name__ == "__main__":
    # List of stock ticker symbols
    NiftyIT = ['INFY.NS', 'TCS.NS']
    NiftyMetal = ['HINDALCO.NS','TATASTEEL.NS','JINDALSTEL.NS', 'VEDL.NS','ICICIBANK.NS']
    NiftyTelecom = ['BHARTIARTL.NS','TATACOMM.NS','IDEA.NS']
    NityBank = ['HDFCBANK.NS','PNB.NS','SBIN.NS', 'ICICIBANK.NS','AXISBANK.NS','CANBK.NS','BANKBARODA.NS','INDUSINDBK.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'J&KBANK.NS', 'IDBI.NS']
    NIftyFMCG = ['BAJAJCON.NS','ITC.NS', 'HINDUNILVR.NS', 'DABUR.NS','COLPAL.NS']

    ticker = NiftyIT + NiftyMetal + NiftyTelecom + NityBank + NIftyFMCG

    # Initialize an empty list to store breakout information for each stock
    breakout_data_list = []

    # Check breakout for each stock and append to the list
    for stock_symbol in ticker:
        breakout_data = check_breakout(stock_symbol)
        breakout_data_list.append(breakout_data)

    # Create a DataFrame from the list of breakout data
    df = pd.DataFrame(breakout_data_list)

    # Print the DataFrame
    print(df)

            Stock  Previous Day's Close  Today's Close  Breakout Detected
0         INFY.NS           1434.000000    1444.349976               True
1          TCS.NS           3513.850098    3537.750000               True
2     HINDALCO.NS            479.950012     473.399994              False
3    TATASTEEL.NS            128.000000     125.300003              False
4   JINDALSTEL.NS            699.549988     678.799988              False
5         VEDL.NS            230.750000     223.399994              False
6    ICICIBANK.NS            940.299988     930.049988              False
7   BHARTIARTL.NS            925.299988     924.250000              False
8     TATACOMM.NS           1901.750000    1863.949951              False
9         IDEA.NS             12.000000      11.450000              False
10    HDFCBANK.NS           1508.050049    1529.550049               True
11         PNB.NS             83.199997      79.750000              False
12        SBIN.NS            602.950012     586.250000              False
13   ICICIBANK.NS            940.299988     930.049988              False
14    AXISBANK.NS           1041.050049     995.549988              False
15       CANBK.NS            384.450012     373.200012              False
16  BANKBARODA.NS            217.850006     212.399994              False
17  INDUSINDBK.NS           1435.400024    1401.300049              False
18     RBLBANK.NS            255.600006     249.300003              False
19    MAHABANK.NS             49.500000      48.849998              False
20     J&KBANK.NS            107.449997     105.599998              False
21        IDBI.NS             70.599998      69.550003              False
22    BAJAJCON.NS            232.300003     225.949997              False
23         ITC.NS            439.750000     436.100006              False
24  HINDUNILVR.NS           2468.899902    2507.850098               True
25       DABUR.NS            553.599976     555.349976               True
26      COLPAL.NS           1978.400024    1990.550049               True

In [14]:
import yfinance as yf
import pandas as pd

def check_breakdown(ticker_symbol):
    stock = yf.Ticker(ticker_symbol)
    data = stock.history(period="2d")  # Get 2 days of data including today

    # Extract previous day's and today's closing prices
    prev_close = data['Close'].iloc[0]  # Previous day's closing price
    today_close = data['Close'].iloc[1]  # Today's closing price

    # Check if there's a breakdown
    is_breakdown = today_close < prev_close

    return {
        'Stock': ticker_symbol,
        'Previous Day\'s Close': prev_close,
        'Today\'s Close': today_close,
        'Breakdown Detected': is_breakdown
    }

if __name__ == "__main__":
    # List of stock ticker symbols
    NiftyIT = ['INFY.NS', 'TCS.NS']
    NiftyMetal = ['HINDALCO.NS','TATASTEEL.NS','JINDALSTEL.NS', 'VEDL.NS','ICICIBANK.NS']
    NiftyTelecom = ['BHARTIARTL.NS','TATACOMM.NS','IDEA.NS']
    NityBank = ['HDFCBANK.NS','PNB.NS','SBIN.NS', 'ICICIBANK.NS','AXISBANK.NS','CANBK.NS','BANKBARODA.NS','INDUSINDBK.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'J&KBANK.NS', 'IDBI.NS']
    NIftyFMCG = ['BAJAJCON.NS','ITC.NS', 'HINDUNILVR.NS', 'DABUR.NS','COLPAL.NS']

    ticker = NiftyIT + NiftyMetal + NiftyTelecom + NityBank + NIftyFMCG

    # Initialize an empty list to store breakdown information for each stock
    breakdown_data_list = []

    # Check breakdown for each stock and append to the list
    for stock_symbol in ticker:
        breakdown_data = check_breakdown(stock_symbol)
        breakdown_data_list.append(breakdown_data)

    # Create a DataFrame from the list of breakdown data
    df = pd.DataFrame(breakdown_data_list)

    # Print the DataFrame
df

            Stock  Previous Day's Close  Today's Close  Breakdown Detected
0         INFY.NS           1463.449951    1478.699951               False
1          TCS.NS           3589.350098    3621.399902               False
2     HINDALCO.NS            470.549988     472.600006               False
3    TATASTEEL.NS            125.250000     125.900002               False
4   JINDALSTEL.NS            677.849976     683.450012               False
5         VEDL.NS            222.000000     222.699997               False
6    ICICIBANK.NS            940.849976     945.200012               False
7   BHARTIARTL.NS            928.849976     926.049988                True
8     TATACOMM.NS           1850.300049    1837.800049                True
9         IDEA.NS             11.200000      10.950000                True
10    HDFCBANK.NS           1535.750000    1534.050049                True
11         PNB.NS             77.099998      76.750000                True
12        SBIN.NS            592.150024     594.250000               False
13   ICICIBANK.NS            940.849976     945.200012               False
14    AXISBANK.NS           1003.250000    1000.950012                True
15       CANBK.NS            371.299988     375.299988               False
16  BANKBARODA.NS            212.550003     215.300003               False
17  INDUSINDBK.NS           1401.849976    1434.800049               False
18     RBLBANK.NS            242.300003     247.500000               False
19    MAHABANK.NS             48.799999      48.549999                True
20     J&KBANK.NS            107.400002     114.000000               False
21        IDBI.NS             68.599998      69.750000               False
22    BAJAJCON.NS            229.850006     231.649994               False
23         ITC.NS            436.049988     442.149994               False
24  HINDUNILVR.NS           2519.550049    2499.399902                True
25       DABUR.NS            550.750000     547.150024                True
26      COLPAL.NS           1997.599976    1992.550049                True

#### Support resistance of stocks

In [15]:
import yfinance as yf
import pandas as pd

def calculate_support_resistance(ticker_symbol, lookback_days=90):
    stock = yf.Ticker(ticker_symbol)
    data = stock.history(period=f"{lookback_days}d")

    # Calculate support and resistance levels
    support_level = data['Low'].min()
    resistance_level = data['High'].max()

    return {
        'Stock': ticker_symbol,
        'Support Level': support_level,
        'Resistance Level': resistance_level
    }

if __name__ == "__main__":


    # Initialize an empty list to store support and resistance information for each stock
    support_resistance_data_list = []

    # Calculate support and resistance for each stock and append to the list
    for stock_symbol in ticker_symbols:
        support_resistance_data = calculate_support_resistance(stock_symbol)
        support_resistance_data_list.append(support_resistance_data)

    # Create a DataFrame from the list of support and resistance data
    df = pd.DataFrame(support_resistance_data_list)

    # Print the DataFrame
print(df)

            Stock  Support Level  Resistance Level
0         INFY.NS    1262.250000       1518.400024
1          TCS.NS    3147.814401       3634.949951
2     HINDALCO.NS     401.726913        508.899994
3    TATASTEEL.NS     102.262333        135.000000
4   JINDALSTEL.NS     506.375458        722.799988
5         VEDL.NS     208.000000        288.450012
6    ICICIBANK.NS     899.891622        997.500000
7   BHARTIARTL.NS     809.083513        948.700012
8     TATACOMM.NS    1247.980480       1957.349976
9         IDEA.NS       6.950000         12.500000
10    HDFCBANK.NS    1489.250000       1757.500000
11         PNB.NS      49.560197         83.500000
12        SBIN.NS     553.799988        621.900024
13   ICICIBANK.NS     899.891622        997.500000
14    AXISBANK.NS     908.331324       1047.500000
15       CANBK.NS     291.649994        386.500000
16  BANKBARODA.NS     176.854922        219.649994
17  INDUSINDBK.NS    1237.919409       1475.650024
18     RBLBANK.NS     151.902636        256.700012
19    MAHABANK.NS      26.606782         51.900002
20     J&KBANK.NS      53.594553        115.900002
21        IDBI.NS      52.183691         74.750000
22    BAJAJCON.NS     178.154001        262.399994
23         ITC.NS     433.299988        499.700012
24  HINDUNILVR.NS    2442.899902       2769.649902
25       DABUR.NS     539.022460        594.313183
26      COLPAL.NS    1569.000000       2096.000000

In [21]:
import yfinance as yf
import pandas as pd

def calculate_support_resistance(ticker_symbol, lookback_days=90):
    stock = yf.Ticker(ticker_symbol)
    data = stock.history(period=f"{lookback_days}d")

    # Calculate support and resistance levels
    support_level = data['Low'].min()
    resistance_level = data['High'].max()

    return {
        'Stock': ticker_symbol,
        'Support Level': support_level,
        'Resistance Level': resistance_level
    }

def check_breakout(ticker_symbol):
    stock = yf.Ticker(ticker_symbol)
    data = stock.history(period="2d")  # Get 2 days of data including today

    # Extract previous day's and today's closing prices
    prev_close = data['Close'].iloc[0]  # Previous day's closing price
    today_close = data['Close'].iloc[1]  # Today's closing price

    # Check if there's a breakout
    is_breakout = today_close > prev_close

    return {
        'Stock': ticker_symbol,
        'Previous Day\'s Close': prev_close,
        'Today\'s Close': today_close,
        'Breakout Detected': is_breakout
    }

def check_breakdown(ticker_symbol):
    stock = yf.Ticker(ticker_symbol)
    data = stock.history(period="2d")  # Get 2 days of data including today

    # Extract previous day's and today's closing prices
    prev_close = data['Close'].iloc[0]  # Previous day's closing price
    today_close = data['Close'].iloc[1]  # Today's closing price

    # Check if there's a breakdown
    is_breakdown = today_close < prev_close

    return {
        'Stock': ticker_symbol,
        'Previous Day\'s Close': prev_close,
        'Today\'s Close': today_close,
        'Breakdown Detected': is_breakdown
    }

if __name__ == "__main__":


    # Initialize an empty list to store data for each stock
    stock_data_list = []

        # List of stock ticker symbols
    NiftyIT = ['INFY.NS', 'TCS.NS']
    NiftyMetal = ['HINDALCO.NS','TATASTEEL.NS','JINDALSTEL.NS', 'VEDL.NS','ICICIBANK.NS']
    NiftyTelecom = ['BHARTIARTL.NS','TATACOMM.NS','IDEA.NS']
    NityBank = ['HDFCBANK.NS','PNB.NS','SBIN.NS', 'ICICIBANK.NS','AXISBANK.NS','CANBK.NS','BANKBARODA.NS','INDUSINDBK.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'J&KBANK.NS', 'IDBI.NS']
    NIftyFMCG = ['BAJAJCON.NS','ITC.NS', 'HINDUNILVR.NS', 'DABUR.NS','COLPAL.NS']

    ticker = NiftyIT + NiftyMetal + NiftyTelecom + NityBank + NIftyFMCG

    # Calculate support, resistance, breakout, and breakdown for each stock and append to the list
    for stock_symbol in ticker:
        support_resistance_data = calculate_support_resistance(stock_symbol)
        breakout_data = check_breakout(stock_symbol)
        breakdown_data = check_breakdown(stock_symbol)

        stock_data = {**support_resistance_data, **breakout_data, **breakdown_data}
        stock_data_list.append(stock_data)

    # Create a DataFrame from the list of data
    df = pd.DataFrame(stock_data_list)

    # Print the DataFrame
df

,Stock,Support Level,Resistance Level,Previous Day's Close,Today's Close,Breakout Detected,Breakdown Detected
0,INFY.NS,1262.250000,1518.400024,1463.449951,1478.699951,True,False
1,TCS.NS,3147.814401,3634.949951,3589.350098,3621.399902,True,False
2,HINDALCO.NS,401.726913,508.899994,470.549988,472.600006,True,False
3,TATASTEEL.NS,102.262333,135.000000,125.250000,125.900002,True,False
4,JINDALSTEL.NS,506.375458,722.799988,677.849976,683.450012,True,False
5,VEDL.NS,208.000000,288.450012,222.000000,222.699997,True,False
6,ICICIBANK.NS,899.891622,997.500000,940.849976,945.200012,True,False
7,BHARTIARTL.NS,809.083513,948.700012,928.849976,926.049988,False,True
8,TATACOMM.NS,1247.980480,1957.349976,1850.300049,1837.800049,False,True
9,IDEA.NS,6.950000,12.500000,11.200000,10.950000,False,True
10,HDFCBANK.NS,1489.250000,1757.500000,1535.750000,1534.050049,False,True
11,PNB.NS,49.560197,83.500000,77.099998,76.750000,False,True
12,SBIN.NS,553.799988,621.900024,592.150024,594.250000,True,False
13,ICICIBANK.NS,899.891622,997.500000,940.849976,945.200012,True,False
14,AXISBANK.NS,908.331324,1047.500000,1003.250000,1000.950012,False,True
15,CANBK.NS,291.649994,386.500000,371.299988,375.299988,True,False
16,BANKBARODA.NS,176.854922,219.649994,212.550003,215.300003,True,False
17,INDUSINDBK.NS,1237.919409,1475.650024,1401.849976,1434.800049,True,False
18,RBLBANK.NS,151.902636,256.700012,242.300003,247.500000,True,False
19,MAHABANK.NS,26.606782,51.900002,48.799999,48.549999,False,True
20,J&KBANK.NS,53.594553,115.900002,107.400002,114.000000,True,False
21,IDBI.NS,52.183691,74.750000,68.599998,69.750000,True,False
22,BAJAJCON.NS,178.154001,262.399994,229.850006,231.649994,True,False
23,ITC.NS,433.299988,499.700012,436.049988,442.149994,True,False
24,HINDUNILVR.NS,2442.899902,2769.649902,2519.550049,2499.399902,False,True
25,DABUR.NS,539.022460,594.313183,550.750000,547.150024,False,True
26,COLPAL.NS,1569.000000,2096.000000,1997.599976,1992.550049,False,True

#### Rewrite entire code in class

In [23]:
import yfinance as yf
import pandas as pd

class StockAnalyzer:
    def __init__(self, ticker_symbol, lookback_days=90):
        self.ticker_symbol = ticker_symbol
        self.lookback_days = lookback_days

    def calculate_support_resistance(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period=f"{self.lookback_days}d")

        support_level = data['Low'].min()
        resistance_level = data['High'].max()

        return {
            'Stock': self.ticker_symbol,
            'Support Level': support_level,
            'Resistance Level': resistance_level
        }

    def check_breakout(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period="2d")

        prev_close = data['Close'].iloc[0]
        today_close = data['Close'].iloc[1]

        is_breakout = today_close > prev_close

        return {
            'Stock': self.ticker_symbol,
            'Previous Day\'s Close': prev_close,
            'Today\'s Close': today_close,
            'Breakout Detected': is_breakout
        }

    def check_breakdown(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period="2d")

        prev_close = data['Close'].iloc[0]
        today_close = data['Close'].iloc[1]

        is_breakdown = today_close < prev_close

        return {
            'Stock': self.ticker_symbol,
            'Previous Day\'s Close': prev_close,
            'Today\'s Close': today_close,
            'Breakdown Detected': is_breakdown
        }

if __name__ == "__main__":
    # List of stock ticker symbols
    NiftyIT = ['INFY.NS', 'TCS.NS']
    NiftyMetal = ['HINDALCO.NS','TATASTEEL.NS','JINDALSTEL.NS', 'VEDL.NS','ICICIBANK.NS']
    NiftyTelecom = ['BHARTIARTL.NS','TATACOMM.NS','IDEA.NS']
    NityBank = ['HDFCBANK.NS','PNB.NS','SBIN.NS', 'ICICIBANK.NS','AXISBANK.NS','CANBK.NS','BANKBARODA.NS','INDUSINDBK.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'J&KBANK.NS', 'IDBI.NS']
    NIftyFMCG = ['BAJAJCON.NS','ITC.NS', 'HINDUNILVR.NS', 'DABUR.NS','COLPAL.NS']

    ticker = NiftyIT + NiftyMetal + NiftyTelecom + NityBank + NIftyFMCG

    # Initialize an empty list to store data for each stock
    stock_data_list = []

    # Calculate support, resistance, breakout, and breakdown for each stock and append to the list
    for stock_symbol in ticker:
        analyzer = StockAnalyzer(stock_symbol)
        support_resistance_data = analyzer.calculate_support_resistance()
        breakout_data = analyzer.check_breakout()
        breakdown_data = analyzer.check_breakdown()

        stock_data = {**support_resistance_data, **breakout_data, **breakdown_data}
        stock_data_list.append(stock_data)

    # Create a DataFrame from the list of data
    df = pd.DataFrame(stock_data_list)

    # Print the DataFrame
df

,Stock,Support Level,Resistance Level,Previous Day's Close,Today's Close,Breakout Detected,Breakdown Detected
0,INFY.NS,1262.250000,1518.400024,1463.449951,1478.699951,True,False
1,TCS.NS,3147.814401,3634.949951,3589.350098,3621.399902,True,False
2,HINDALCO.NS,401.726913,508.899994,470.549988,472.600006,True,False
3,TATASTEEL.NS,102.262333,135.000000,125.250000,125.900002,True,False
4,JINDALSTEL.NS,506.375458,722.799988,677.849976,683.450012,True,False
5,VEDL.NS,208.000000,288.450012,222.000000,222.699997,True,False
6,ICICIBANK.NS,899.891622,997.500000,940.849976,945.200012,True,False
7,BHARTIARTL.NS,809.083513,948.700012,928.849976,926.049988,False,True
8,TATACOMM.NS,1247.980480,1957.349976,1850.300049,1837.800049,False,True
9,IDEA.NS,6.950000,12.500000,11.200000,10.950000,False,True
10,HDFCBANK.NS,1489.250000,1757.500000,1535.750000,1534.050049,False,True
11,PNB.NS,49.560197,83.500000,77.099998,76.750000,False,True
12,SBIN.NS,553.799988,621.900024,592.150024,594.250000,True,False
13,ICICIBANK.NS,899.891622,997.500000,940.849976,945.200012,True,False
14,AXISBANK.NS,908.331324,1047.500000,1003.250000,1000.950012,False,True
15,CANBK.NS,291.649994,386.500000,371.299988,375.299988,True,False
16,BANKBARODA.NS,176.854922,219.649994,212.550003,215.300003,True,False
17,INDUSINDBK.NS,1237.919409,1475.650024,1401.849976,1434.800049,True,False
18,RBLBANK.NS,151.902636,256.700012,242.300003,247.500000,True,False
19,MAHABANK.NS,26.606782,51.900002,48.799999,48.549999,False,True
20,J&KBANK.NS,53.594553,115.900002,107.400002,114.000000,True,False
21,IDBI.NS,52.183691,74.750000,68.599998,69.750000,True,False
22,BAJAJCON.NS,178.154001,262.399994,229.850006,231.649994,True,False
23,ITC.NS,433.299988,499.700012,436.049988,442.149994,True,False
24,HINDUNILVR.NS,2442.899902,2769.649902,2519.550049,2499.399902,False,True
25,DABUR.NS,539.022460,594.313183,550.750000,547.150024,False,True
26,COLPAL.NS,1569.000000,2096.000000,1997.599976,1992.550049,False,True

In [30]:
import yfinance as yf
import pandas as pd

class StockAnalyzer:
    def __init__(self, ticker_symbol, lookback_days=90):
        self.ticker_symbol = ticker_symbol
        self.lookback_days = lookback_days

    def calculate_support_resistance(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period=f"{self.lookback_days}d")

        support_level = data['Low'].min()
        resistance_level = data['High'].max()

        return {
            'Stock': self.ticker_symbol,
            'Support Level': support_level,
            'Resistance Level': resistance_level
        }

    def check_breakout(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period="2d")

        prev_close = data['Close'].iloc[0]
        today_close = data['Close'].iloc[1]

        is_breakout = today_close > prev_close

        return {
            'Stock': self.ticker_symbol,
            'Previous Day\'s Close': prev_close,
            'Today\'s Close': today_close,
            'Breakout Detected': is_breakout
        }

    def check_breakdown(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period="2d")

        prev_close = data['Close'].iloc[0]
        today_close = data['Close'].iloc[1]

        is_breakdown = today_close < prev_close

        return {
            'Stock': self.ticker_symbol,
            'Previous Day\'s Close': prev_close,
            'Today\'s Close': today_close,
            'Breakdown Detected': is_breakdown
        }

    def check_resistance_breakout(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period="5d")

        prev_high = data['High'].iloc[0]
        today_high = data['High'].iloc[1]

        is_breakout = today_high > prev_high

        return {
            'Stock': self.ticker_symbol,
            'Previous Day\'s Low': prev_high,
            'Today\'s Low': today_high,
            'resistance Breakout Detected': is_breakout
        }

    def check_support_breakdown(self):
        stock = yf.Ticker(self.ticker_symbol)
        data = stock.history(period="5d")

        prev_low = data['Low'].iloc[0]
        today_low = data['Low'].iloc[1]

        is_breakdown = today_low < prev_low

        return {
            'Stock': self.ticker_symbol,
            'Previous Day\'s Low': prev_low,
            'Today\'s Low': today_low,
            'Support Breakdown Detected': is_breakdown
        }

if __name__ == "__main__":
    # List of stock ticker symbols
    NiftyIT = ['INFY.NS', 'TCS.NS']
    NiftyMetal = ['HINDALCO.NS','TATASTEEL.NS','JINDALSTEL.NS', 'VEDL.NS','ICICIBANK.NS']
    NiftyTelecom = ['BHARTIARTL.NS','TATACOMM.NS','IDEA.NS']
    NityBank = ['HDFCBANK.NS','PNB.NS','SBIN.NS', 'ICICIBANK.NS','AXISBANK.NS','CANBK.NS','BANKBARODA.NS','INDUSINDBK.NS', 'RBLBANK.NS', 'MAHABANK.NS', 'J&KBANK.NS', 'IDBI.NS']
    NIftyFMCG = ['BAJAJCON.NS','ITC.NS', 'HINDUNILVR.NS', 'DABUR.NS','COLPAL.NS']

    ticker = NiftyIT + NiftyMetal + NiftyTelecom + NityBank + NIftyFMCG

    # Initialize an empty list to store data for each stock
    stock_data_list = []

    # Calculate support, resistance, breakout, breakdown, support breakout, and support breakdown for each stock and append to the list
    for stock_symbol in ticker:
        analyzer = StockAnalyzer(stock_symbol)
        support_resistance_data = analyzer.calculate_support_resistance()
        breakout_data = analyzer.check_breakout()
        breakdown_data = analyzer.check_breakdown()
        resistance_breakout_data = analyzer.check_resistance_breakout()
        support_breakdown_data = analyzer.check_support_breakdown()

        stock_data = {**support_resistance_data, **breakout_data, **breakdown_data,
                      **resistance_breakout_data, **support_breakdown_data}
        stock_data_list.append(stock_data)

    # Create a DataFrame from the list of data
    df = pd.DataFrame(stock_data_list)

    # Print the DataFrame
df

,Stock,Support Level,Resistance Level,Previous Day's Close,Today's Close,Breakout Detected,Breakdown Detected,Previous Day's Low,Today's Low,resistance Breakout Detected,Support Breakdown Detected
0,INFY.NS,1262.250000,1518.400024,1463.449951,1478.699951,True,False,1416.000000,1420.300049,False,False
1,TCS.NS,3147.814401,3634.949951,3589.350098,3621.399902,True,False,3505.550049,3480.100098,False,True
2,HINDALCO.NS,401.726913,508.899994,470.549988,472.600006,True,False,474.200012,476.600006,False,False
3,TATASTEEL.NS,102.262333,135.000000,125.250000,125.900002,True,False,127.550003,127.250000,False,True
4,JINDALSTEL.NS,506.375458,722.799988,677.849976,683.450012,True,False,686.299988,690.000000,False,False
5,VEDL.NS,208.000000,288.450012,222.000000,222.699997,True,False,210.000000,225.100006,True,False
6,ICICIBANK.NS,899.891622,997.500000,940.849976,945.200012,True,False,943.700012,939.000000,False,True
7,BHARTIARTL.NS,809.083513,948.700012,928.849976,926.049988,False,True,921.799988,916.049988,False,True
8,TATACOMM.NS,1247.980480,1957.349976,1850.300049,1837.800049,False,True,1888.900024,1894.750000,False,False
9,IDEA.NS,6.950000,12.500000,11.200000,10.950000,False,True,11.600000,11.400000,False,True
10,HDFCBANK.NS,1489.250000,1757.500000,1535.750000,1534.050049,False,True,1522.300049,1506.000000,False,True
11,PNB.NS,49.560197,83.500000,77.099998,76.750000,False,True,79.500000,79.800003,True,False
12,SBIN.NS,553.799988,621.900024,592.150024,594.250000,True,False,591.299988,589.599976,True,True
13,ICICIBANK.NS,899.891622,997.500000,940.849976,945.200012,True,False,943.700012,939.000000,False,True
14,AXISBANK.NS,908.331324,1047.500000,1003.250000,1000.950012,False,True,1024.500000,1032.599976,True,False
15,CANBK.NS,291.649994,386.500000,371.299988,375.299988,True,False,372.500000,373.600006,True,False
16,BANKBARODA.NS,176.854922,219.649994,212.550003,215.300003,True,False,212.000000,212.000000,True,False
17,INDUSINDBK.NS,1237.919409,1475.650024,1401.849976,1434.800049,True,False,1399.300049,1420.000000,False,False
18,RBLBANK.NS,151.902636,256.700012,242.300003,247.500000,True,False,243.050003,248.250000,True,False
19,MAHABANK.NS,26.606782,51.900002,48.799999,48.549999,False,True,47.049999,47.250000,True,False
20,J&KBANK.NS,53.594549,115.900002,107.400002,114.000000,True,False,105.050003,105.500000,True,False
21,IDBI.NS,52.183691,74.750000,68.599998,69.750000,True,False,70.349998,70.000000,True,True
22,BAJAJCON.NS,178.154001,262.399994,229.850006,231.649994,True,False,222.000000,224.850006,True,False
23,ITC.NS,433.299988,499.700012,436.049988,442.149994,True,False,439.200012,439.250000,False,False
24,HINDUNILVR.NS,2442.899902,2769.649902,2519.550049,2499.399902,False,True,2450.500000,2461.800049,True,False
25,DABUR.NS,539.022460,594.313183,550.750000,547.150024,False,True,546.750000,546.099976,True,True
26,COLPAL.NS,1569.000000,2096.000000,1997.599976,1992.550049,False,True,1981.349976,1969.150024,True,True